### ISSUE TITLE
Noise pollution GL style

### ISSUE THREAD

**Issue by klokan** [OctoGEO/eovation#1]
The GL style for noise pollution vector tiles (https://github.com/OctoGEO/osm-noise-pollution) with transparency.

**Comment by jirik** [comment]
- Noise with satellite layer: https://github.com/OctoGEO/eovation/blob/master/noise/style.satellite.json
- Only noise (for raster tiles): https://github.com/OctoGEO/eovation/blob/master/noise/style.noise-only.json
