### ISSUE TITLE
Noise pollution raster tiles global

### ISSUE THREAD

**Issue by klokan** [OctoGEO/eovation#2]
Let's create raster tiles for the whole world with the noise pollution style #1 

We can reuse our tilehosting.com platform - the idea is to get global raster tiles with transparency for visualization in any web browser (including WebGL Earth).

@martinmikita

**Comment by jirik** [comment]
Prepared style: https://github.com/OctoGEO/eovation/blob/master/noise/style.noise-only.json

**Comment by MartinMikita** [comment]
Raster tiles:
 - hidpi 
https://maps.tilehosting.com/c/klokantech/styles/noise-pollution-only/{z}/{x}/{y}@2x.png?key=2rAee65H2Kxb4K8dcZTl
 - normal https://maps.tilehosting.com/c/klokantech/styles/noise-pollution-only/{z}/{x}/{y}.png?key=2rAee65H2Kxb4K8dcZTl

**Comment by MartinMikita** [comment]
Done.
