### ISSUE TITLE
Demo of our satellite hybrid with high-res aerial from Prague inside

### ISSUE THREAD

**Issue by klokan** [OctoGEO/eovation#3]
Our main product is about combining satellite and aerial opendata into one satellite map. 

For this hackathon, we could produce for the first time a global raster tile service with Satellite + Aerial map with labels and demonstrate our technology on the ESA Sentinel-2 and OpenData from Prague.

**Comment by jirik** [comment]
- [code](https://github.com/OctoGEO/eovation/tree/master/satellite)
- [preview](https://rawgit.com/OctoGEO/eovation/master/satellite/index.html#ll=50.08617,14.41361;alt=327;h=-1.211;t=-0.688)

preview linked also from readme

**Comment by MartinMikita** [comment]
The style was changed and deployed to contain more levels of opacity, starting at zoom 10, through 11 and 12, finished at 13 with full opacity for aerial layers.
