### ISSUE TITLE
Landcover timelapse

### ISSUE THREAD

**Issue by MartinMikita** [OctoGEO/eovation#4]
Prepare timelapse of using 27 Landcover datasets

Datasets are now available on IBM cloud machine:
http://159.122.92.89:8082/

**Comment by MartinMikita** [comment]
Test of the landcover overzoom on 1 dataset for 0-10: http://159.122.92.89:8084/#1995-z10/ol3

1 dataset took ~13m 35s

**Comment by jirik** [comment]
Implemented by https://github.com/OctoGEO/eovation/commit/0f4d9b777890ff76239ebc301a10f74b4018cdff
